import streamlit as st

import streamlit as st  #type: ignore
import pandas as pd  
import os

# Title of the app
st.title("Qualitative Performance Assessment of EndoDAC and Depth Pro Models")

# Questionnaire description
st.write(
    "The video in the center shows a colonoscopy, while the two side videos (left and right) "
    "represent depth maps generated by two predictive models, where blue indicates deeper areas "
    "and red indicates shallower areas. \n"
    "Which of the two side videos (left or right) do you think best reflects reality in terms of accuracy in depth estimation?"
)

# First question: are you a clinician?
clinician = st.radio("Are you a clinician?", ["Yes", "No"])

# If you are a clinician, what level of experience?
experience_level = None
procedures_performed = None
if clinician == "Yes":
    experience_level = st.radio("What is your experience level?", ["Specializzando", "Resident", "Esperto"])
    procedures_performed = st.radio(
        "How many endoscopic procedures have you performed?",
        ["<50", "Between 50 and 100", ">100"]
    )

# Second question: name
name = st.text_input("Please enter your name")

# Paths to the videos in the 'videos' folder
video_paths = [
    "./VideoColonoscopy3.mp4",
    "./VideoColonoscopy4.mp4",
    "./VideoColonoscopy5.mp4",
    "./VideoColonoscopy6.mp4",
    "./VideoColonoscopy7.mp4",
    "./VideoColonoscopy8.mp4",
    "./VideoColonoscopy9.mp4",
    "./VideoColonoscopy10.mp4",
    "./VideoColonoscopy11.mp4",
    "./VideoColonoscopy12.mp4",
]

# Session state
if "question_index" not in st.session_state:
    st.session_state["question_index"] = 0
if "responses" not in st.session_state:
    st.session_state["responses"] = [None] * len(video_paths)

# If the user has entered the name, proceed with the questionnaire
if name:
    st.header("Questionnaire")
    
    question_index = st.session_state["question_index"]
    
    st.subheader(f"Question {question_index + 1}")
    st.video(video_paths[question_index])  # Here we use the relative video path
    
    existing_response = st.session_state["responses"][question_index]
    default_index = 0 if existing_response == "Left" else 1 if existing_response == "Right" else None
    
    response = st.radio(
        "Which of the two side videos (left or right) do you think best reflects reality in terms of accuracy in depth estimation?", 
        ["Left", "Right"], 
        key=f"question_{question_index}",
        index=default_index
    )
    
    st.session_state["responses"][question_index] = response
    
    col1, col2 = st.columns([1, 1])
    with col1:
        if st.button("Previous") and question_index > 0:
            st.session_state["question_index"] -= 1
            st.rerun()
    with col2:
        if st.button("Next") and question_index < len(video_paths) - 1:
            st.session_state["question_index"] += 1
            st.rerun()
    
    # Save answers in the excel file
    if question_index == len(video_paths) - 1 and st.button("Submit Answers"):
        file_path = "responses.xlsx"
        
        # Create the dictionary for the data row
        new_data = {
            "Name": name,
            "Clinician": clinician,
            "Experience Level": experience_level if clinician == "Yes" else None,
            "Procedures Performed": procedures_performed if clinician == "Yes" else None,
        }

        # Add the responses to the dictionary
        for i in range(len(video_paths)):
            new_data[f"Question {i+1}"] = st.session_state["responses"][i] if st.session_state["responses"][i] else "No Response"

        df_new = pd.DataFrame([new_data])  # Create the DataFrame from the list of dictionaries

        # If the file exists, load it and append the new data
        if os.path.exists(file_path):
            df_existing = pd.read_excel(file_path)
            df_final = pd.concat([df_existing, df_new], ignore_index=True)
        else:
            df_final = df_new
        
        df_final.to_excel(file_path, index=False)
        st.success("Your answers have been saved!")

        st.stop()
